# Generated by Django 4.2.15 on 2024-08-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fid',
            new_name='id',
        ),
    ]
