# Generated by Django 4.2.15 on 2024-08-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainee',
            new_name='Track',
        ),
    ]
